formatting:
  MaximumLineLength:
    active: true
    maxLineLength: 155
  NoWildcardImports:
    active: false

style:
  MaxLineLength:
    active: false
    maxLineLength: 160
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
  MagicNumber:
    active: false
    ignoreNumbers: '-1,0,1,2'
    ignoreHashCodeFunction: false
    ignorePropertyDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
  ThrowsCount:
    active: true
    max: 3
  UnnecessaryAbstractClass:
    active: false

naming:
  TopLevelPropertyNaming:
    active: true
    excludes: [ '**/test/**', '**/commonTest/**']
    constantPattern: '[_A-Za-z0-9]*'
    propertyPattern: '[_A-Za-z0-9]*'
    privatePropertyPattern: '_?[A-Za-z][_A-Za-z0-9]*'

exceptions:
  TooGenericExceptionCaught:
    active: false
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - Exception
      - IllegalMonitorStateException
      - NullPointerException
      - IndexOutOfBoundsException
      - RuntimeException
      - Throwable
  TooGenericExceptionThrown:
    active: false
    exceptionNames:
      - Error
      - Exception
      - Throwable
      - RuntimeException
complexity:
  LongMethod:
    active: true
    threshold: 65
